### ISSUE TITLE
Retour intégration : graphisme et photos

### ISSUE THREAD

**Issue by m-zoff** [lardepa/lindex#28]
**— général** 
- [x] Couleur du noir > color: #313138;
- [x]  Toutes les border: 1px 
- [x] ajouter un border-right: 1px à la colonne de gauche 
- [x] #41

**— home**

_menu Vertical home_
- [x] border-top: 1px solid #313138;

**— selections**
_https://lardepa.github.io/lindex/#/selections_
Img miniature, Largeur 1/4 col et la hauteur s’adapte à la case qui dépend du nb de lignes
- [x] border-top: 1px solid #000;
- [x] padding-left: 1rem;

**— Sélection personnalité 1**
_https://lardepa.github.io/lindex/#/selections/recBb6NHdfNisYSjI_

_image_
- [ ] ratio (bon pour toutes les images cover) > 100*65
_En dessous_ 
- [x] margin : 0

_Carte_ 
- [ ] même ratio que les images de cover 100/65

- [x] Le picto est centré  dans la largeur dans un rectangle blanc, largeur fixe (3rem) et hauteur dépend du nb de ligne à droite.

**— page lieu**
- [x] Les images au format paysage s’adapte à la largeur de la page (avec un padding-right : 1rem)
- [x] Les images en mode portrait sont centrées dans la largeur avec 1rem de padding entre chaque media

**— page Explorer**
_https://lardepa.github.io/lindex/#/explorer_

**— page Parcours au pluriel**
_https://lardepa.github.io/lindex/#/parcours_

_Liste des parcours_ 
- [x] Img miniature, Largeur 1/4 col et la hauteur s’adapte à la case qui dépend du nb de lignes (du coup ça  crop)
border-top: 1px solid #000;

**— page Parcours au pluriel**
_https://lardepa.github.io/lindex/#/parcours/recit6lDBhqoxoJn9_

- [x] Ligne entre les points sur la carte en pointillés > stroke-dasharray: 0 8;

- [x] Ajouter 1rem entre les photos
